### ISSUE TITLE
The file templates/aide.conf.erb has CR at end of lines, which breaks aide

### ISSUE THREAD

**Issue by bjvrielink** [indiana-university/puppet-aide#1]
Both 'puppet module install' and r10k result in a template with CR LF at end of lines, but downloading the tarball from forge.puppet.com or a git clone from github result in a good template with only LF at the end of line. Because of this, I only caught this error when the module was already deployed on the Puppet server...

Please remove all CR (^M) characters from all text files (or at least the template).

```
# aide
1:syntax error:
1:Error while reading configuration:
Configuration error
```

**Comment by kekogya** [comment]
@bjvrielink, what editor are you using to view the file? I am not seeing the CR LF in my editor. Also, what OS are you running it on?

**Comment by bjvrielink** [comment]
"Editor" is a little overkill, but I also did check with vim, as well as with file, cat and od. Tried it on both Centos7 and Debian Testing:

 ```
H voojagig  root  ~  puppet module install iu-aide
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Notice: Installing -- do not interrupt ...
/etc/puppetlabs/code/environments/production/modules
└─┬ iu-aide (v1.0.2)
  ├── puppet-cron (v1.3.1)
  └─┬ puppetlabs-concat (v5.3.0)
    ├── puppetlabs-stdlib (v5.2.0)
    └── puppetlabs-translate (v1.2.0)
 H voojagig  root  ~  file /etc/puppetlabs/code/environments/production/modules/aide/templates/aide.conf.erb 
/etc/puppetlabs/code/environments/production/modules/aide/templates/aide.conf.erb: ASCII text, with CRLF line terminators
 H voojagig  root  ~  cat -A !$ | head -5
cat -A /etc/puppetlabs/code/environments/production/modules/aide/templates/aide.conf.erb | head -5
# This file is managed by puppet^M$
^M$
# Configuration file for AIDE.^M$
^M$
#Variables are required for openscap-security-guide^M$
 H voojagig  root  ~  od -c /etc/puppetlabs/code/environments/production/modules/aide/templates/aide.conf.erb | head -5
0000000   #       T   h   i   s       f   i   l   e       i   s       m
0000020   a   n   a   g   e   d       b   y       p   u   p   p   e   t
0000040  \r  \n  \r  \n   #       C   o   n   f   i   g   u   r   a   t
0000060   i   o   n       f   i   l   e       f   o   r       A   I   D
0000100   E   .  \r  \n  \r  \n   #   V   a   r   i   a   b   l   e   s
```

**Comment by kekogya** [comment]
I used your command `cat -A aide.conf.erb | head -5` and below is what I see(I am not seeing those characters):
```
root@automate:/etc/puppetlabs/code/environments/production/modules/aide/templates# cat -A aide.conf.erb | head -5
# This file is managed by puppet$
$
# Configuration file for AIDE.$
$
#Variables are required for openscap-security-guide$
```
I made some changes to the module repo yesterday so would it possible for you to try using the git repo directly and let me know if  `vim` or `cat` still shows those characters on your end?

**Comment by bjvrielink** [comment]
As I mentioned in my original issue report, a git clone from github works fine. Most likely because of the .gitattributes file. The problem is that the file as pulled from forge.puppet.com has the wrong line endings.

**Comment by kekogya** [comment]
@bjvrielink, Please give it another try and let me know if the issue still persist. I have updated the forge module

**Comment by bjvrielink** [comment]
This new version works. Thank you.

**Comment by kekogya** [comment]
Glad to hear. Thanks for bringing the issue to my attention.
