### ISSUE TITLE
Tag v2.0.0

### ISSUE THREAD

**Issue by gibbs** [indiana-university/puppet-aide#10]
Is it possible you can add the `v2.0.0` tag to this repository?

Thanks for your work on this module - I've been using it for a few years now.

**Comment by kekogya** [comment]
> Is it possible you can add the `v2.0.0` tag to this repository?
> 
> Thanks for your work on this module - I've been using it for a few years now.

I have added the `v2.0.0` tag. Sorry for any inconvenience this may have caused.
