### ISSUE TITLE
Optionally specify $conf_path and --config parameter in CRON job

### ISSUE THREAD

**Issue by bschonec** [indiana-university/puppet-aide#13]
I'm working with 3rd party vendors doing CIS and security checking.  The current CRON job:

0 0 * * *  root  nice ionice -c3 /usr/sbin/aide --config /etc/aide.conf --check

Fails the regex tests that the vendors do for AIDE due to '--config /etc/aide.conf' being specified.  I figure it's easier to update this module than to convince the vendors to update their regular expressions.

I propose an option to exclude the '--config /etc/aide' part of the CRON job and just let aide use its default of /etc/aide.conf.

**Comment by bschonec** [comment]
#14

**Comment by kekogya** [comment]
Resolved!
