### ISSUE TITLE
mail command with "mail_only_on_changes"

### ISSUE THREAD

**Issue by andrewtwemlow** [indiana-university/puppet-aide#4]
when "mail_only_on_changes" is set, the `-E` flag is being used on the mail command but no command is being specified for execution. Resulting in error messages being produced.
The `-E` flag should be followed immediately with the command, it is then interpreting `-s` as the command to execute.

```

mail: Unknown command: -s
mail: Cannot parse address `localhost - AIDE Integrity Check' (while expanding `localhost - AIDE Integrity Check'): Malformed email address

```

cron.pp
```
        command => "AIDE_OUT=$(${settings} 2>&1) || echo \"\${AIDE_OUT}\" | ${cat_path} -v | ${mail_path} -E -s ${email_subject}",
```

Suggestion would be to use the same mail command as $mail_only_on_changes == false

```
        command => "AIDE_OUT=$(${settings} 2>&1) || echo \"\${AIDE_OUT}\" | ${cat_path} -v | ${mail_path} -s ${email_subject}",
```

Testing on Ubuntu 18.04

**Comment by kekogya** [comment]
@twem, When I run that command, I don't get the error message that you are describing. For reference, below is the command I am running:
`AIDE_OUT=$(aide --config /etc/aide/aide.conf --check); echo ${AIDE_OUT} | cat -v | /usr/bin/mail -E -s "localhost - AIDE Integrity Check" johndoe@doe.edu`. I'm I missing something? I run this on Ubuntu 18.04 as well.

**Comment by kekogya** [comment]
> when "mail_only_on_changes" is set, the `-E` flag is being used on the mail command but no command is being specified for execution. Resulting in error messages being produced.
> The `-E` flag should be followed immediately with the command, it is then interpreting `-s` as the command to execute.
> 
> ```
> 
> mail: Unknown command: -s
> mail: Cannot parse address `localhost - AIDE Integrity Check' (while expanding `localhost - AIDE Integrity Check'): Malformed email address
> ```
> 
> cron.pp
> 
> ```
>         command => "AIDE_OUT=$(${settings} 2>&1) || echo \"\${AIDE_OUT}\" | ${cat_path} -v | ${mail_path} -E -s ${email_subject}",
> ```
> 
> Suggestion would be to use the same mail command as $mail_only_on_changes == false
> 
> ```
>         command => "AIDE_OUT=$(${settings} 2>&1) || echo \"\${AIDE_OUT}\" | ${cat_path} -v | ${mail_path} -s ${email_subject}",
> ```
> 
> Testing on Ubuntu 18.04

Per the mail manpage:
The `-E` flag does this: Don't send messages with an empty body.

**Comment by andrewtwemlow** [comment]
I must have a different version of mail on U18.04

```

twem@localhost:~$ man mail | grep '\-E' -A 2
       -E, --exec=COMMAND
              execute COMMAND

twem@localhost:~$ uname -a
Linux s005-pup-ukw-01 5.0.0-1028-azure #30~18.04.1-Ubuntu SMP Fri Dec 6 11:47:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
twem@localhost:~$ which mail
/usr/bin/mail
twem@localhost:~$
```

**Comment by kekogya** [comment]
Must be.

```
sadmin@server-admin:~# man mail | grep '\-E' -A 2
     -E      Don't send messages with an empty body.

sadmin@server-admin:~# uname -a
Linux server-admin 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
sadmin@server-admin:~# which mail
/usr/bin/mail
sadmin@server-admin:~#

sadmin@server-admin:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
admin@server-admin:~#
```

**Comment by kekogya** [comment]
The latest module has been posted to the forge.

**Comment by andrewtwemlow** [comment]
Which mail package are you using?

(different server to before)

```
andrew@server:~$ man mail | grep '\-E' -A 2
       -E, --exec=COMMAND
              execute COMMAND

andrew@server:~$ uname -a
Linux unifi-video 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

andrew@server:~$ which mail
/usr/bin/mail

andrew@server:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

andrew@server:~$ ls -l /usr/bin/mail
lrwxrwxrwx 1 root root 22 Jan 24 19:26 /usr/bin/mail -> /etc/alternatives/mail
andrew@server:~$ ls -l /etc/alternatives/mail
lrwxrwxrwx 1 root root 23 Jan 24 19:26 /etc/alternatives/mail -> /usr/bin/mail.mailutils
andrew@server:~$ ls -l /usr/bin/mail.mailutils
-rwxr-xr-x 1 root root 197200 Nov  7  2017 /usr/bin/mail.mailutils

andrew@server:~$ dpkg -S /usr/bin/mail.mailutils
mailutils: /usr/bin/mail.mailutils

```

**Comment by kekogya** [comment]
Looks like we are using `bsd-mailx`. It appears the `-E` flag for mailx and mailutils do different things per the manpage.

```
sadmin@server-admin:~# ls -l /usr/bin/mail
lrwxrwxrwx 1 root root 22 Sep  5 16:54 /usr/bin/mail -> /etc/alternatives/mail
sadmin@server-admin:~# ls -l /etc/alternatives/mail
lrwxrwxrwx 1 root root 18 Sep  5 16:54 /etc/alternatives/mail -> /usr/bin/bsd-mailx
sadmin@server-admin:~# ls -l /usr/bin/bsd-mailx
-rwxr-xr-x 1 root root 108792 Apr 14  2017 /usr/bin/bsd-mailx
sadmin@server-admin:~# ls -l /usr/bin/mail.mailutils
-rwxr-xr-x 1 root root 197200 Nov  7  2017 /usr/bin/mail.mailutils
sadmin@server-admin:~# dpkg -S /usr/bin/mail.mailutils
mailutils: /usr/bin/mail.mailutils
sadmin@server-admin:~# dpkg -S /usr/bin/bsd-mailx
bsd-mailx: /usr/bin/bsd-mailx
```
